Repository CSCfi/etsin-finder, pull requests merged in 2020-12, with the labels that each got.

#615 Cscfairmeta 790 test and refactor submit buttons in frontend
  etsin_finder/frontend/__tests__/__snapshots__/qvain.test.jsx.snap
  etsin_finder/frontend/__tests__/__snapshots__/qvain.test.legacy.jsx.snap
  etsin_finder/frontend/__tests__/qvain.apiv2.test.jsx
  etsin_finder/frontend/__tests__/qvain.submitButtonsV2.test.jsx
  etsin_finder/frontend/__tests__/qvain.test.jsx
  etsin_finder/frontend/__tests__/submitButtons.test.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/stickyHeader.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/submitButton.styled.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/submitButtons.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/submitButtonsV1.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/submitButtonsV2.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/submitResponse.jsx
  etsin_finder/frontend/js/components/qvain/views/main/index.jsx
  etsin_finder/frontend/js/stores/view/qvain/index.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.description.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.otherIdentifier.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.submit.js
  etsin_finder/frontend/js/utils/constants.js
Labels: new feature

#639 CSCFAIRMETA-821: Refactor SSO & SAML
  etsin_finder/app_config.py
  etsin_finder/authentication_fairdata_sso.py
  etsin_finder/frontend/js/components/general/keepAlive/index.jsx
  etsin_finder/frontend/js/components/general/navigation/loginButton.jsx
  etsin_finder/saml_config.py
  etsin_finder/views.py
Labels: refactor-improve

#637 CSCFAIRMETA-665: Add focus indicator to filter items.
  etsin_finder/frontend/js/components/search/filterResults/filterSection.jsx
Labels: refactor-improve

#638 CSCFAIRMETA-835: Fix error in search title
  etsin_finder/frontend/js/stores/view/accessibility.js
Labels: bugfix

#640 CSCFAIRMETA-837: Project and SubmitButtons fixes
  etsin_finder/frontend/__tests__/__snapshots__/qvain.test.jsx.snap
  etsin_finder/frontend/__tests__/__snapshots__/qvain.test.legacy.jsx.snap
  etsin_finder/frontend/js/components/qvain/fields/project/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/temporalAndSpatial/temporal/TemporalList.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/stickyHeader.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/submitButtons.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/submitResponse.jsx
  etsin_finder/frontend/js/components/qvain/views/main/index.jsx
  etsin_finder/frontend/js/stores/view/qvain/qvain.project.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.temporals.js
Labels: bugfix

#642 CSCFAIRMETA-486-Etsin-buttons-in-Firefox
  etsin_finder/frontend/js/components/dataset/formatChanger.jsx
  etsin_finder/frontend/js/components/dataset/formatselect.jsx
  etsin_finder/frontend/js/components/dataset/versionChanger.jsx
  etsin_finder/frontend/js/components/dataset/versionselect.jsx
Labels: bugfix

#643 JYU-Logo
  etsin_finder/frontend/static/images/catalog_logos/jyu_keskitetty_kaksikielinen.png
Labels: bugfix

#641 CSCFAIRMETA-830: Etsin dataset tab button styling fixes
  etsin_finder/frontend/js/components/dataset/contact/index.jsx
  etsin_finder/frontend/js/components/dataset/description.jsx
  etsin_finder/frontend/js/components/dataset/formatselect.jsx
  etsin_finder/frontend/js/components/dataset/versionselect.jsx
Labels: bugfix

#644 CSCFAIRMETA-838: Removed datsets not visible
  etsin_finder/authorization.py
Labels: bugfix

#645 CSCFAIRMETA-840: Clear submit response between datasets
  etsin_finder/frontend/js/components/qvain/views/main/index.jsx
  etsin_finder/frontend/js/stores/view/qvain/index.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.submit.js
Labels: bugfix

#646 Merge test to stable v0.9.34-rc1
  etsin_finder/app_config.py
  etsin_finder/authentication_fairdata_sso.py
  etsin_finder/authorization.py
  etsin_finder/frontend/__tests__/__snapshots__/qvain.test.jsx.snap
  etsin_finder/frontend/__tests__/__snapshots__/qvain.test.legacy.jsx.snap
  etsin_finder/frontend/__tests__/qvain.apiv2.test.jsx
  etsin_finder/frontend/__tests__/qvain.submitButtonsV2.test.jsx
  etsin_finder/frontend/__tests__/qvain.test.jsx
  etsin_finder/frontend/__tests__/submitButtons.test.jsx
  etsin_finder/frontend/js/components/dataset/contact/index.jsx
  etsin_finder/frontend/js/components/dataset/description.jsx
  etsin_finder/frontend/js/components/dataset/formatChanger.jsx
  etsin_finder/frontend/js/components/dataset/formatselect.jsx
  etsin_finder/frontend/js/components/dataset/versionChanger.jsx
  etsin_finder/frontend/js/components/dataset/versionselect.jsx
  etsin_finder/frontend/js/components/general/keepAlive/index.jsx
  etsin_finder/frontend/js/components/general/navigation/loginButton.jsx
  etsin_finder/frontend/js/components/qvain/fields/project/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/temporalAndSpatial/temporal/TemporalList.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/stickyHeader.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/submitButton.styled.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/submitButtons.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/submitButtonsV1.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/submitButtonsV2.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/submitResponse.jsx
  etsin_finder/frontend/js/components/qvain/views/main/index.jsx
  etsin_finder/frontend/js/components/search/filterResults/filterSection.jsx
  etsin_finder/frontend/js/stores/view/accessibility.js
  etsin_finder/frontend/js/stores/view/qvain/index.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.description.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.otherIdentifier.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.project.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.submit.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.temporals.js
  etsin_finder/frontend/js/utils/constants.js
  etsin_finder/frontend/static/images/catalog_logos/jyu_keskitetty_kaksikielinen.png
  etsin_finder/saml_config.py
  etsin_finder/views.py
Labels: release-candidate

#648 CSCFAIRMETA-835: Fix error in search tab
  etsin_finder/frontend/js/stores/view/accessibility.js
Labels: bugfix

#647 fixed new cumulative dataset bug
  etsin_finder/frontend/__tests__/qvain.apiv2.test.jsx
  etsin_finder/frontend/js/stores/view/qvain/index.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.submit.js
Labels: bugfix

#649 Merge test to stable v0.9.34-rc2
  etsin_finder/frontend/__tests__/qvain.apiv2.test.jsx
  etsin_finder/frontend/js/stores/view/accessibility.js
  etsin_finder/frontend/js/stores/view/qvain/index.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.submit.js
Labels: release-candidate

#650 Merge stable to master v0.9.34-rc2
  etsin_finder/app_config.py
  etsin_finder/authentication_fairdata_sso.py
  etsin_finder/authorization.py
  etsin_finder/frontend/__tests__/__snapshots__/qvain.test.jsx.snap
  etsin_finder/frontend/__tests__/__snapshots__/qvain.test.legacy.jsx.snap
  etsin_finder/frontend/__tests__/qvain.apiv2.test.jsx
  etsin_finder/frontend/__tests__/qvain.submitButtonsV2.test.jsx
  etsin_finder/frontend/__tests__/qvain.test.jsx
  etsin_finder/frontend/__tests__/submitButtons.test.jsx
  etsin_finder/frontend/js/components/dataset/contact/index.jsx
  etsin_finder/frontend/js/components/dataset/description.jsx
  etsin_finder/frontend/js/components/dataset/formatChanger.jsx
  etsin_finder/frontend/js/components/dataset/formatselect.jsx
  etsin_finder/frontend/js/components/dataset/versionChanger.jsx
  etsin_finder/frontend/js/components/dataset/versionselect.jsx
  etsin_finder/frontend/js/components/general/keepAlive/index.jsx
  etsin_finder/frontend/js/components/general/navigation/loginButton.jsx
  etsin_finder/frontend/js/components/qvain/fields/project/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/temporalAndSpatial/temporal/TemporalList.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/stickyHeader.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/submitButton.styled.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/submitButtons.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/submitButtonsV1.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/submitButtonsV2.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/submitResponse.jsx
  etsin_finder/frontend/js/components/qvain/views/main/index.jsx
  etsin_finder/frontend/js/components/search/filterResults/filterSection.jsx
  etsin_finder/frontend/js/stores/view/accessibility.js
  etsin_finder/frontend/js/stores/view/qvain/index.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.description.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.otherIdentifier.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.project.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.submit.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.temporals.js
  etsin_finder/frontend/js/utils/constants.js
  etsin_finder/frontend/static/images/catalog_logos/jyu_keskitetty_kaksikielinen.png
  etsin_finder/saml_config.py
  etsin_finder/views.py
Labels: release

#656 CSCFAIRMETA-818: Clear dataset deletion error when modal is closed
  etsin_finder/frontend/js/components/qvain/views/datasets/removeModal.jsx
Labels: bugfix

#657 CSCFAIRMETA-827: Clear filepicker v2 when switching to another dataset
  etsin_finder/frontend/js/stores/view/qvain/index.js
Labels: bugfix

#654 CSCFAIRMETA-28: Accessibility landmark fixes
  etsin_finder/frontend/__tests__/__snapshots__/qvain.test.jsx.snap
  etsin_finder/frontend/js/components/general/header/index.jsx
  etsin_finder/frontend/js/components/general/skipToContent.jsx
  etsin_finder/frontend/js/components/qvain/fields/description/keywords/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/description/otherIdentifier/index.jsx
  etsin_finder/frontend/js/components/qvain/general/card/index.jsx
  etsin_finder/frontend/js/components/qvain/general/input/stringArray.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/editor.styled.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/header.jsx
  etsin_finder/frontend/js/components/qvain/views/landingPage/description.jsx
  etsin_finder/frontend/js/index.jsx
  etsin_finder/frontend/js/layout/cookiesNotification.jsx
  etsin_finder/frontend/js/layout/index.jsx
  etsin_finder/frontend/locale/english.js
  etsin_finder/frontend/locale/finnish.js
  etsin_finder/frontend/package-lock.json
  etsin_finder/frontend/package.json
Labels: refactor-improve

#631 CSCFAIRMETA-825: Use Field of Science codes and categories
  etsin_finder/frontend/__tests__/__snapshots__/qvain.test.jsx.snap
  etsin_finder/frontend/js/components/qvain/fields/description/fieldOfScience/index.jsx
  etsin_finder/frontend/js/components/qvain/general/input/select.jsx
  etsin_finder/frontend/js/components/qvain/utils/select.js
Labels: new feature

#632 CSCFAIRMETA-823: Button styling tweaks
  etsin_finder/frontend/js/components/qvain/fields/project/FundingOrganization.jsx
  etsin_finder/frontend/js/components/qvain/fields/temporalAndSpatial/temporal/TemporalList.jsx
  etsin_finder/frontend/js/components/qvain/general/buttons/buttonContainers.jsx
  etsin_finder/frontend/js/components/qvain/general/buttons/commonButtons.jsx
  etsin_finder/frontend/js/components/qvain/general/input/datepicker.jsx
  etsin_finder/frontend/js/components/qvain/general/input/stringArray.jsx
  etsin_finder/frontend/js/components/qvain/general/section/fieldListAdd.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/deprecatedState.jsx
Labels: refactor-improve

#633 CSCFAIRMETA-824: Use language setting for language tabs
  etsin_finder/frontend/__tests__/qvain.test.jsx
  etsin_finder/frontend/js/components/qvain/fields/description/titleAndDescription/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/history/provenance/form/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/history/relatedResource/form/index.jsx
  etsin_finder/frontend/js/components/qvain/general/input/translationTab.jsx
Labels: new feature

#652 Cscfairmeta 822 new cumulative dataset doesnt get updated
  etsin_finder/frontend/__tests__/qvain.apiv2.test.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/cumulativeState.jsx
  etsin_finder/frontend/js/stores/view/qvain/qvain.submit.js
Labels: bugfix

#636 CSCFAIRMETA-829: Change accessibility links in footer
  etsin_finder/frontend/js/layout/footer.jsx
Labels: refactor-improve

#634 CSCFAIRMETA-805: Upgrade styled-components to v5
  etsin_finder/frontend/__tests__/__snapshots__/qvain.test.jsx.snap
  etsin_finder/frontend/package-lock.json
  etsin_finder/frontend/package.json
Labels: refactor-improve

#655 CSCFAIRMETA-834: Feature flags
  etsin_finder/app.py
  etsin_finder/app_config.py
  etsin_finder/finder.py
  etsin_finder/flags.py
  etsin_finder/frontend/__tests__/__snapshots__/qvain.test.legacy.jsx.snap
  etsin_finder/frontend/__tests__/cumulativeState.test.jsx
  etsin_finder/frontend/__tests__/download.test.jsx
  etsin_finder/frontend/__tests__/general.flaggedComponent.test.jsx
  etsin_finder/frontend/__tests__/metadataModal.legacy.test.jsx
  etsin_finder/frontend/__tests__/metadataModal.test.jsx
  etsin_finder/frontend/__tests__/qvain.accessType.test.jsx
  etsin_finder/frontend/__tests__/qvain.actors.test.jsx
  etsin_finder/frontend/__tests__/qvain.files.legacy.jsx
  etsin_finder/frontend/__tests__/qvain.files.test.jsx
  etsin_finder/frontend/__tests__/qvain.metadata.store.test.js
  etsin_finder/frontend/__tests__/qvain.test.jsx
  etsin_finder/frontend/__tests__/qvain.test.legacy.jsx
  etsin_finder/frontend/__tests__/qvainPas.legacy.test.jsx
  etsin_finder/frontend/__tests__/qvainPas.test.jsx
  etsin_finder/frontend/__tests__/removeModal.test.jsx
  etsin_finder/frontend/__tests__/submitButtons.test.jsx
  etsin_finder/frontend/js/components/general/flaggedComponent.jsx
  etsin_finder/frontend/js/stores/domain/env.flags.js
  etsin_finder/frontend/js/stores/domain/env.js
  etsin_finder/resources.py
  tests/basetest.py
  tests/test_flags.py
  tests/test_request_utils.py
Labels: new feature

#658 CSCFAIRMETA-834: Feature flag bugfixes
  etsin_finder/frontend/js/stores/domain/env.flags.js
  etsin_finder/frontend/js/stores/domain/env.js
Labels: bugfix

#659 CSCFAIRMETA-832: Open first non-empty language tab by default
  etsin_finder/frontend/__tests__/__snapshots__/qvain.test.legacy.jsx.snap
  etsin_finder/frontend/__tests__/locale.test.jsx
  etsin_finder/frontend/js/components/qvain/fields/description/titleAndDescription/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/history/provenance/form/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/history/relatedResource/form/index.jsx
  etsin_finder/frontend/js/components/qvain/general/input/translationTab.jsx
  etsin_finder/frontend/js/stores/view/locale.js
Labels: refactor-improve

#635 CSCFAIRMETA-801: Support separate internal and public download service urls
  etsin_finder/app_config.py
  etsin_finder/download_service_v2.py
  tests/test_download.py
Labels: new feature

#653 CSCFAIRMETA-831: Update the copy to clipboard for identifier
  etsin_finder/frontend/js/components/dataset/identifier.jsx
  etsin_finder/frontend/locale/english.js
  etsin_finder/frontend/locale/finnish.js
  etsin_finder/frontend/package.json
Labels: refactor-improve

#664 CSCFAIRMETA-842: Prevent errors from moving addition button
  etsin_finder/frontend/js/components/qvain/general/input/stringArray.jsx
Labels: refactor-improve

#663 Travis: Update package-lock.json
  etsin_finder/frontend/package-lock.json
Labels: refactor-improve
