Repository CSCfi/etsin-finder, pull requests merged in 2021-06, with the labels that each got.

#846 CSCFAIRMETA-1043: Refactor StickyHeader and SubmitButtons
  etsin_finder/frontend/__tests__/combined/qvain/__snapshots__/qvain.test.jsx.snap
  etsin_finder/frontend/__tests__/components/qvain/qvain.main.test.jsx
  etsin_finder/frontend/__tests__/components/qvain/qvain.stickyHeader.test.jsx
  etsin_finder/frontend/__tests__/components/qvain/qvain.submitButtons.test.jsx
  etsin_finder/frontend/js/components/qvain/general/card/index.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/dataset.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/stickyHeader.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/submitButtons.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/submitButtonsV2.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/submitResponse.jsx
  etsin_finder/frontend/js/components/qvain/views/main/index.jsx
  etsin_finder/frontend/js/stores/view/qvain/index.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.submit.js
Labels: bugfix, refactor-improve

#849 CSCFAIRADM-590: Add memcached (to Docker)
  docker-compose-with-nginx.yml
  docker-compose.yml
Labels: refactor-improve

#847 Cscfairmeta 1057 readonly when user is no longer in the project
  etsin_finder/frontend/__tests__/combined/qvain/a11y/qvain.files.a11y.test.jsx
  etsin_finder/frontend/__tests__/combined/qvain/metadataModal.test.jsx
  etsin_finder/frontend/__tests__/combined/qvain/qvain.fileForm.test.jsx
  etsin_finder/frontend/__tests__/combined/qvain/qvain.files.test.jsx
  etsin_finder/frontend/__tests__/combined/qvain/qvainPas.test.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/ida/forms/directoryForm.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/ida/forms/fileForm.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/ida/selectedItemsDropdown.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/ida/selectedItemsTreeItem.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/metadataModal/index.jsx
  etsin_finder/frontend/js/stores/domain/auth.js
  etsin_finder/frontend/js/stores/index.js
  etsin_finder/frontend/js/stores/view/common.files.loaders.js
  etsin_finder/frontend/js/stores/view/qvain/index.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.files.js
  etsin_finder/frontend/locale/english/qvain.files.js
  etsin_finder/frontend/locale/finnish/qvain.files.js
Labels: new feature

#851 CSCFAIRMETA-1079: Remove DOI confirmation modal
  etsin_finder/frontend/__tests__/components/qvain/qvain.submitButtons.test.jsx
  etsin_finder/frontend/__tests__/stores/view/qvain.apiv2.test.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/doiModal.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/submitButtons.jsx
  etsin_finder/frontend/js/stores/view/qvain/qvain.submit.js
  etsin_finder/frontend/locale/english/qvain.js
  etsin_finder/frontend/locale/finnish/qvain.js
Labels: refactor-improve

#850 CSCFAIRMETA-1074: Support bearer token for download service
  etsin_finder/app_config.py
  etsin_finder/services/download_service.py
  tests/test_download.py
Labels: new feature

#852 Cscfairmeta 1041 time periods without start/end date
  etsin_finder/frontend/__tests__/components/qvain/qvain.provenance.test.jsx
  etsin_finder/frontend/__tests__/components/qvain/qvain.temporal.test.jsx
  etsin_finder/frontend/__tests__/stores/view/qvain.temporal.test.js
  etsin_finder/frontend/js/components/qvain/fields/history/provenance/handleSave.js
  etsin_finder/frontend/js/components/qvain/fields/temporalAndSpatial/temporal/TemporalList.jsx
  etsin_finder/frontend/js/components/qvain/utils/formValidation.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.provenances.js
  etsin_finder/frontend/locale/english/qvain.temporalAndSpatial.js
  etsin_finder/frontend/locale/english/qvain.validationMessages.js
  etsin_finder/frontend/locale/finnish/qvain.temporalAndSpatial.js
  etsin_finder/frontend/locale/finnish/qvain.validationMessages.js
Labels: new feature

#845 Cscfairmeta 813 cross ref api poc
  etsin_finder/frontend/__tests__/components/qvain/qvain.relatedResource.test.jsx
  etsin_finder/frontend/__tests__/stores/view/qvain.crossRef.test.js
  etsin_finder/frontend/js/components/qvain/fields/history/relatedResource/relatedResourceContent.jsx
  etsin_finder/frontend/js/components/qvain/fields/history/relatedResource/resourceSearchField.jsx
  etsin_finder/frontend/js/stores/index.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.crossRef.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.field.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.relatedResources.js
  etsin_finder/frontend/js/utils/urls.js
  etsin_finder/frontend/locale/english/qvain.history.js
  etsin_finder/frontend/locale/finnish/qvain.history.js
  etsin_finder/utils/flags.py
Labels: flagged, new feature

#853 CSCFAIRMETA-1096: Translation spelling fixes
  etsin_finder/frontend/locale/english/index.js
  etsin_finder/frontend/locale/english/qvain.history.js
  etsin_finder/frontend/locale/english/qvain.temporalAndSpatial.js
  etsin_finder/frontend/locale/finnish/index.js
Labels: bugfix
