Repository CSCfi/etsin-finder, pull requests merged in 2021-03, with the labels that each got.

#742 Merge stable to master v0.9.37-rc-1
  etsin_finder/frontend/__tests__/combined/general/a11y/cookiesNotification.a11y.test.jsx
  etsin_finder/frontend/js/components/dataset/content.jsx
  etsin_finder/frontend/js/components/dataset/data/idaResourcesV2/errorMessage.jsx
  etsin_finder/frontend/js/components/dataset/data/idaResourcesV2/fileTreeItem.jsx
  etsin_finder/frontend/js/components/dataset/index.jsx
  etsin_finder/frontend/js/components/general/files/items.jsx
  etsin_finder/frontend/js/components/general/files/tree.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/ida/addItemsTree.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/ida/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/project/FundingAgency.jsx
  etsin_finder/frontend/js/components/qvain/fields/project/FundingOrganization.jsx
  etsin_finder/frontend/js/components/qvain/fields/project/index.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/editor.styled.jsx
  etsin_finder/frontend/js/layout/cookiesNotification.jsx
  etsin_finder/frontend/js/styles/globalStyles.jsx
  etsin_finder/frontend/locale/english.js
  etsin_finder/frontend/locale/finnish.js
  etsin_finder/frontend/static/images/closeCookiesNotification.svg
  etsin_finder/frontend/static/images/closeCookiesNotificationHover.svg
  etsin_finder/resources/common_resources_v2.py
  etsin_finder/views/dev_views.py
Labels: release

#717 CSCFAIRMETA-918: Etsin frontpage accessibility tests
  etsin_finder/frontend/__tests__/combined/etsin/a11y/frontpage.a11y.test.jsx
  etsin_finder/frontend/__tests__/combined/etsin/a11y/header.a11y.test.jsx
  etsin_finder/frontend/js/components/frontpage/keyValues.jsx
Labels: refactor-improve

#722 CSCFAIRMETA-920: Etsin dataset page accessibility tests
  etsin_finder/frontend/__tests__/__testdata__/dataset.att.js
  etsin_finder/frontend/__tests__/combined/etsin/a11y/dataset.a11y.test.jsx
  etsin_finder/frontend/__tests__/combined/qvain/a11y/qvain.landingPage.a11y.test.jsx
  etsin_finder/frontend/js/components/dataset/data/index.jsx
  etsin_finder/frontend/js/components/dataset/description.jsx
  etsin_finder/frontend/js/components/dataset/events/index.jsx
  etsin_finder/frontend/js/components/dataset/formatselect.jsx
  etsin_finder/frontend/js/components/dataset/maps/index.jsx
  etsin_finder/frontend/js/components/dataset/sidebar/index.jsx
  etsin_finder/frontend/js/components/dataset/sidebar/sidebarItem.jsx
  etsin_finder/frontend/js/components/dataset/sidebar/special/importImages.js
  etsin_finder/frontend/js/components/dataset/sidebar/special/logo.jsx
  etsin_finder/frontend/js/components/qvain/general/section/tooltip.jsx
  etsin_finder/frontend/locale/english.js
  etsin_finder/frontend/locale/finnish.js
Labels: refactor-improve

#724 CSCFAIRMETA-919: Etsin search page accessibility tests
  etsin_finder/frontend/__tests__/__testdata__/searchResults.data.js
  etsin_finder/frontend/__tests__/combined/etsin/a11y/search.a11y.test.jsx
  etsin_finder/frontend/js/components/search/results.jsx
Labels: refactor-improve

#725 CSCFAIRMETA-922: Etsin modals accessibility tests
  etsin_finder/frontend/__tests__/combined/etsin/a11y/accessRights.a11y.jsx
  etsin_finder/frontend/__tests__/combined/etsin/a11y/contact.a11y.test.jsx
  etsin_finder/frontend/__tests__/combined/etsin/a11y/info.a11y.test.jsx
Labels: refactor-improve

#726 CSCFAIRMETA-927: Qvain filepicker accessibility tests
  etsin_finder/frontend/__tests__/__testdata__/qvain.files.data.js
  etsin_finder/frontend/__tests__/__testdata__/referenceData.data.js
  etsin_finder/frontend/__tests__/combined/qvain/a11y/qvain.files.a11y.test.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/ida/forms/directoryForm.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/ida/forms/fileForm.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/ida/index.jsx
Labels: refactor-improve

#728 CSCFAIRMETA-921: Etsin filepicker accessibility tests
  etsin_finder/frontend/__tests__/__testdata__/dataset.ida.js
  etsin_finder/frontend/__tests__/combined/etsin/a11y/etsin.files.a11y.test.jsx
  etsin_finder/frontend/js/components/dataset/data/idaResourcesV2/fileTreeItem.jsx
  etsin_finder/frontend/js/components/dataset/data/idaResourcesV2/iconButton.jsx
Labels: refactor-improve

#730 CSCFAIRMETA-926: Qvain editor modals accessibility tests
  etsin_finder/frontend/__tests__/__testdata__/dataset.att.js
  etsin_finder/frontend/__tests__/__testdata__/qvain.files.data.js
  etsin_finder/frontend/__tests__/__testdata__/referenceData.data.js
  etsin_finder/frontend/__tests__/combined/qvain/a11y/qvain.modals.actor.a11y.test.jsx
  etsin_finder/frontend/__tests__/combined/qvain/a11y/qvain.modals.provenance.a11y.test.jsx
  etsin_finder/frontend/__tests__/combined/qvain/a11y/qvain.modals.relatedResource.a11y.test.jsx
  etsin_finder/frontend/__tests__/combined/qvain/a11y/qvain.modals.spatial.a11y.jsx
  etsin_finder/frontend/js/components/qvain/fields/history/provenance/ProvenanceFieldContent.jsx
  etsin_finder/frontend/js/components/qvain/fields/history/provenance/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/temporalAndSpatial/spatial/SpatialFieldContent.jsx
  etsin_finder/frontend/js/components/qvain/fields/temporalAndSpatial/spatial/index.jsx
Labels: refactor-improve

#687 CSCFAIRMETA-853 tests for common.files.utils
  etsin_finder/frontend/__tests__/stores/view/common.files.utils.test.js
Labels: refactor-improve

#662 Give a more descriptive alt text
  etsin_finder/frontend/js/components/dataset/sidebar/index.jsx
  etsin_finder/frontend/js/components/general/image.jsx
  etsin_finder/frontend/locale/english.js
  etsin_finder/frontend/locale/finnish.js
Labels: refactor-improve

#737 CSCFAIRMETA-960, CSCFAIRMETA-973, CSCFAIRMETA-975 new Matomo implementation
  etsin_finder/frontend/__tests__/combined/etsin/__snapshots__/filterSection.test.jsx.snap
  etsin_finder/frontend/__tests__/combined/etsin/filterItem.test.jsx
  etsin_finder/frontend/__tests__/combined/qvain/__snapshots__/qvain.test.legacy.jsx.snap
  etsin_finder/frontend/__tests__/combined/qvain/a11y/qvain.editor.a11y.test.jsx
  etsin_finder/frontend/__tests__/combined/qvain/qvain.test.jsx
  etsin_finder/frontend/__tests__/combined/qvain/qvain.test.legacy.jsx
  etsin_finder/frontend/__tests__/components/qvain/qvain.submitButtonsV2.test.jsx
  etsin_finder/frontend/js/components/dataset/data/index.jsx
  etsin_finder/frontend/js/components/dataset/description.jsx
  etsin_finder/frontend/js/components/dataset/events/index.jsx
  etsin_finder/frontend/js/components/dataset/maps/index.jsx
  etsin_finder/frontend/js/components/errorpage/index.jsx
  etsin_finder/frontend/js/components/frontpage/index.jsx
  etsin_finder/frontend/js/components/header/index.jsx
  etsin_finder/frontend/js/components/qvain/views/datasets/dataset.jsx
  etsin_finder/frontend/js/components/qvain/views/datasets/index.jsx
  etsin_finder/frontend/js/components/qvain/views/datasets/removeModal.jsx
  etsin_finder/frontend/js/components/qvain/views/datasets/table.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/dataset.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/submitButtonsV2.jsx
  etsin_finder/frontend/js/components/qvain/views/landingPage/index.jsx
  etsin_finder/frontend/js/components/qvain/views/main/index.jsx
  etsin_finder/frontend/js/components/search/filterResults/clearFilters.jsx
  etsin_finder/frontend/js/components/search/filterResults/filterItem.jsx
  etsin_finder/frontend/js/components/search/filterResults/filterSection.jsx
  etsin_finder/frontend/js/components/search/filterResults/filterToggle.jsx
  etsin_finder/frontend/js/components/search/index.jsx
  etsin_finder/frontend/js/components/search/searchBar.jsx
  etsin_finder/frontend/js/layout/content.jsx
  etsin_finder/frontend/js/layout/loggedInRoute.jsx
  etsin_finder/frontend/js/stores/index.js
  etsin_finder/frontend/js/stores/tracking/index.js
  etsin_finder/frontend/js/stores/view/elasticquery.js
  etsin_finder/frontend/js/utils/tracking/index.js
  etsin_finder/frontend/static/index.template.ejs
  etsin_finder/utils/flags.py
Labels: new feature

#751 CSCFAIRMETA-966: Keep polling when package status is STARTED
  etsin_finder/frontend/__tests__/__testdata__/download.data.js
  etsin_finder/frontend/__tests__/combined/etsin/download.test.jsx
  etsin_finder/frontend/js/components/dataset/data/idaResourcesV2/downloadActions.js
  etsin_finder/frontend/js/stores/view/packages.js
  etsin_finder/frontend/js/utils/constants.js
Labels: bugfix

#752 CSCFAIRMETA-974: Fix turning dataset non-cumulative
  etsin_finder/frontend/__tests__/combined/qvain/__snapshots__/qvain.test.legacy.jsx.snap
  etsin_finder/frontend/js/stores/view/qvain/qvain.submit.js
Labels: bugfix

#753 CSCFAIRMETA-932: Update eslint to 7.21.0
  etsin_finder/frontend/.eslintrc
  etsin_finder/frontend/js/app.jsx
  etsin_finder/frontend/js/components/dataset/accessRights.jsx
  etsin_finder/frontend/js/components/dataset/data/breadcrumbs.jsx
  etsin_finder/frontend/js/components/dataset/data/fileIcon.jsx
  etsin_finder/frontend/js/components/dataset/data/tableItem.jsx
  etsin_finder/frontend/js/components/dataset/description.jsx
  etsin_finder/frontend/js/components/dataset/index.jsx
  etsin_finder/frontend/js/components/dataset/tabs.jsx
  etsin_finder/frontend/js/components/general/announceAndReset/index.jsx
  etsin_finder/frontend/js/components/general/errorBoundary.jsx
  etsin_finder/frontend/js/components/general/keepAlive/idle.jsx
  etsin_finder/frontend/js/components/general/keepAlive/index.jsx
  etsin_finder/frontend/js/components/general/navigation/loginButton.jsx
  etsin_finder/frontend/js/components/general/navigation/settings.jsx
  etsin_finder/frontend/js/components/general/popup.jsx
  etsin_finder/frontend/js/components/qvain/fields/description/issuedDate/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/external/externalFileForm.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/external/externalFiles.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/legacy/directoryForm.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/legacy/fileForm.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/legacy/idaFilePicker.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/legacy/projectSelector.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/legacy/selectedFiles.jsx
  etsin_finder/frontend/js/components/qvain/fields/licenses/embargoExpires.jsx
  etsin_finder/frontend/js/components/qvain/views/datasets/table.jsx
  etsin_finder/frontend/js/components/qvain/views/main/index.jsx
  etsin_finder/frontend/js/components/search/sortResults/index.jsx
  etsin_finder/frontend/js/stores/view/qvain/qvain.actors.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.infrastructure.js
  etsin_finder/frontend/package-lock.json
  etsin_finder/frontend/package.json
Labels: refactor-improve

#750 CSCFAIRMETA-953: Update mobx to 6.1.8
  etsin_finder/frontend/__tests__/combined/qvain/__snapshots__/qvain.test.legacy.jsx.snap
  etsin_finder/frontend/__tests__/stores/view/qvain.apiv2.test.jsx
  etsin_finder/frontend/js/stores/view/common.files.js
  etsin_finder/frontend/js/stores/view/common.files.views.js
  etsin_finder/frontend/js/stores/view/files.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.actors.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.files.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.multiLanguageField.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.provenances.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.restrictionGrounds.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.singleValueField.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.temporals.js
  etsin_finder/frontend/package-lock.json
  etsin_finder/frontend/package.json
Labels: refactor-improve

#749 CSCFAIRMETA-906: Citation modal
  etsin_finder/frontend/__tests__/combined/etsin/a11y/citationModal.a11y.test.jsx
  etsin_finder/frontend/__tests__/utils/cite.test.js
  etsin_finder/frontend/js/components/dataset/citation/citationModal.jsx
  etsin_finder/frontend/js/components/dataset/citation/cite/apa.js
  etsin_finder/frontend/js/components/dataset/citation/cite/chicago.js
  etsin_finder/frontend/js/components/dataset/citation/cite/citationBuilder.js
  etsin_finder/frontend/js/components/dataset/citation/cite/index.js
  etsin_finder/frontend/js/components/dataset/citation/cite/mla.js
  etsin_finder/frontend/js/components/dataset/citation/cite/utils.js
  etsin_finder/frontend/js/components/dataset/copyToClipboard.jsx
  etsin_finder/frontend/js/components/dataset/identifier.jsx
  etsin_finder/frontend/js/components/dataset/index.jsx
  etsin_finder/frontend/js/components/dataset/sidebar/index.jsx
  etsin_finder/frontend/js/components/general/errorBoundary.jsx
  etsin_finder/frontend/js/components/general/modal.jsx
  etsin_finder/frontend/js/components/general/tooltipHover.jsx
  etsin_finder/frontend/js/stores/view/datasetquery.js
  etsin_finder/frontend/js/stores/view/locale.js
  etsin_finder/frontend/locale/english.js
  etsin_finder/frontend/locale/finnish.js
  etsin_finder/utils/flags.py
Labels: new feature

#748 CSCFAIRMETA-970: Fix having too many pages in dataset pagination
  etsin_finder/frontend/js/components/qvain/views/datasets/table.jsx
Labels: bugfix

#754 CSCFAIRMETA-906: Fix citation version numbering
  etsin_finder/frontend/__tests__/utils/cite.test.js
  etsin_finder/frontend/js/components/dataset/citation/citationModal.jsx
  etsin_finder/frontend/js/components/dataset/citation/cite/utils.js
Labels: bugfix

#760 CSCFAIRMETA-994: Fix tab changing to dataset on reload
  etsin_finder/frontend/js/components/dataset/content.jsx
Labels: bugfix

#768 CSCFAIRMETA-993: Remove storybook files
  etsin_finder/frontend/.storybook/addons.js
  etsin_finder/frontend/.storybook/config.js
  etsin_finder/frontend/.storybook/preview-head.html
  etsin_finder/frontend/.storybook/webpack.config.js
  etsin_finder/frontend/package-lock.json
  etsin_finder/frontend/package.json
  etsin_finder/frontend/stories/componentCode.jsx
  etsin_finder/frontend/stories/esRes.js
  etsin_finder/frontend/stories/index.js
  etsin_finder/frontend/stories/metaxRes.js
  etsin_finder/frontend/stories/resourceData.js
  etsin_finder/frontend/stories/sampledata.js
Labels: refactor-improve

#767 CSCFAIRMETA-951: Update leaflet
  etsin_finder/frontend/js/layout/cookiesNotification.jsx
  etsin_finder/frontend/package-lock.json
  etsin_finder/frontend/package.json
Labels: refactor-improve

#772 CSCFAIRMETA-946: Validation fixes
  etsin_finder/frontend/__tests__/combined/qvain/__snapshots__/qvain.test.jsx.snap
  etsin_finder/frontend/__tests__/combined/qvain/__snapshots__/qvain.test.legacy.jsx.snap
  etsin_finder/frontend/__tests__/combined/qvain/qvain.test.jsx
  etsin_finder/frontend/__tests__/components/qvain/validationError.test.jsx
  etsin_finder/frontend/__tests__/stores/view/qvain.apiv2.test.jsx
  etsin_finder/frontend/__tests__/utils/formValidation.test.jsx
  etsin_finder/frontend/js/components/qvain/fields/actors/modal/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/actors/modal/org/orgForm.jsx
  etsin_finder/frontend/js/components/qvain/fields/actors/modal/person/personInput.jsx
  etsin_finder/frontend/js/components/qvain/fields/description/issuedDate/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/dataCatalog.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/external/externalFileForm.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/ida/forms/directoryForm.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/ida/forms/fileForm.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/legacy/directoryForm.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/legacy/fileForm.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/metadataModal/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/history/provenance/handleSave.js
  etsin_finder/frontend/js/components/qvain/fields/history/relatedResource/handleSave.js
  etsin_finder/frontend/js/components/qvain/fields/licenses/embargoExpires.jsx
  etsin_finder/frontend/js/components/qvain/fields/licenses/restrictionGrounds.jsx
  etsin_finder/frontend/js/components/qvain/fields/project/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/project/utils.jsx
  etsin_finder/frontend/js/components/qvain/fields/temporalAndSpatial/spatial/handleSave.js
  etsin_finder/frontend/js/components/qvain/fields/temporalAndSpatial/temporal/handleSave.js
  etsin_finder/frontend/js/components/qvain/general/errors/validationError.jsx
  etsin_finder/frontend/js/components/qvain/utils/formValidation.js
  etsin_finder/frontend/js/components/qvain/views/editor/submitButtons.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/submitButtonsV1.jsx
  etsin_finder/frontend/js/stores/view/qvain/qvain.restrictionGrounds.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.singleValueField.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.spatials.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.submit.js
  etsin_finder/frontend/locale/english.js
  etsin_finder/frontend/locale/finnish.js
  etsin_finder/frontend/package-lock.json
  etsin_finder/frontend/package.json
Labels: bugfix, refactor-improve

#765 CSCFAIRMETA-986: Remove npm update from watch script
  etsin_finder/frontend/package.json
Labels: refactor-improve

#764 CSCFAIRMETA-980: Add email input to package generation modal
  etsin_finder/frontend/js/components/dataset/common/formItems.jsx
  etsin_finder/frontend/js/components/dataset/contact/contactForm.jsx
  etsin_finder/frontend/js/components/dataset/data/idaResourcesV2/confirmPackageModal.jsx
  etsin_finder/frontend/locale/english.js
  etsin_finder/frontend/locale/finnish.js
  etsin_finder/utils/flags.py
Labels: new feature

#763 CSCFAIRMETA-990: Update remote resources data tab
  etsin_finder/frontend/__tests__/__testdata__/externalResources.data.js
  etsin_finder/frontend/__tests__/combined/etsin/a11y/etsin.files.a11y.test.jsx
  etsin_finder/frontend/__tests__/combined/etsin/externalResources.test.jsx
  etsin_finder/frontend/__tests__/combined/qvain/__snapshots__/qvain.test.jsx.snap
  etsin_finder/frontend/__tests__/utils/buildColumns.test.js
  etsin_finder/frontend/js/components/dataset/data/common/dataHeader.jsx
  etsin_finder/frontend/js/components/dataset/data/common/iconButton.jsx
  etsin_finder/frontend/js/components/dataset/data/externalResources/index.jsx
  etsin_finder/frontend/js/components/dataset/data/externalResources/resourceItem.jsx
  etsin_finder/frontend/js/components/dataset/data/idaResourcesV2/fileTreeItem.jsx
  etsin_finder/frontend/js/components/dataset/data/idaResourcesV2/index.jsx
  etsin_finder/frontend/js/components/dataset/data/index.jsx
  etsin_finder/frontend/js/components/general/button.jsx
  etsin_finder/frontend/js/components/general/tooltipHover.jsx
  etsin_finder/frontend/js/utils/buildColumns.js
  etsin_finder/frontend/locale/english.js
  etsin_finder/frontend/locale/finnish.js
Labels: new feature

#759 CSCFAIRMETA-984: Prevent having multiple publishers
  etsin_finder/frontend/__tests__/combined/qvain/__snapshots__/qvain.test.legacy.jsx.snap
  etsin_finder/frontend/__tests__/combined/qvain/qvain.actors.test.jsx
  etsin_finder/frontend/js/components/qvain/fields/actors/modal/actorRoles.jsx
  etsin_finder/frontend/js/stores/view/qvain/qvain.actors.js
Labels: bugfix

#756 CSCFAIRMETA-992: Hide empty lists in sidebar
  etsin_finder/frontend/__tests__/utils/helpers.test.jsx
  etsin_finder/frontend/js/components/dataset/sidebar/index.jsx
  etsin_finder/frontend/js/components/dataset/sidebar/sidebarItem.jsx
  etsin_finder/frontend/js/utils/helpers.jsx
Labels: bugfix

#758 CSCFAIRMETA-831: Identifier improvements
  etsin_finder/frontend/js/components/dataset/copyToClipboard.jsx
  etsin_finder/frontend/js/components/dataset/identifier.jsx
Labels: refactor-improve

#755 CSCFAIRMETA-991: Maintain order of creators
  etsin_finder/frontend/__tests__/combined/qvain/__snapshots__/qvain.actors.test.jsx.snap
  etsin_finder/frontend/__tests__/combined/qvain/__snapshots__/qvain.test.legacy.jsx.snap
  etsin_finder/frontend/__tests__/combined/qvain/qvain.actors.test.jsx
  etsin_finder/frontend/js/stores/view/qvain/qvain.actors.js
Labels: refactor-improve

#775 CSCFAIRMETA-990: Show remote object count in data tab
  etsin_finder/frontend/js/components/dataset/data/common/iconButton.jsx
  etsin_finder/frontend/js/components/dataset/data/externalResources/index.jsx
  etsin_finder/frontend/locale/english.js
  etsin_finder/frontend/locale/finnish.js
Labels: bugfix, refactor-improve
