Repository CSCfi/etsin-finder, pull requests merged in 2021-08, with the labels that each got.

#859 CSCFAIRMETA-1119 fix for provenance not loading spatials and usedEntities
  etsin_finder/frontend/__tests__/stores/view/qvain.spatial.test.js
  etsin_finder/frontend/__tests__/stores/view/usedEntities.test.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.spatials.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.usedEntities.js
Labels: bugfix, javascript

#857 CSCFAIRMETA-1020: Prevent creating packages over 5TB in front-end
  etsin_finder/frontend/__tests__/combined/etsin/a11y/etsin.files.a11y.test.jsx
  etsin_finder/frontend/__tests__/combined/etsin/download.test.jsx
  etsin_finder/frontend/__tests__/stores/view/package.test.js
  etsin_finder/frontend/js/components/dataset/data/idaResources/downloadActions.js
  etsin_finder/frontend/js/components/dataset/data/idaResources/fileTree.jsx
  etsin_finder/frontend/js/components/dataset/data/idaResources/fileTreeItem.jsx
  etsin_finder/frontend/js/components/dataset/data/idaResources/index.jsx
  etsin_finder/frontend/js/stores/view/packages.js
  etsin_finder/frontend/locale/english/index.js
  etsin_finder/frontend/locale/finnish/index.js
Labels: refactor-improve

#858 CSCFAIRMETA-1118 tests for qvain utils
  etsin_finder/utils/qvain_utils.py
  tests/basetest.py
  tests/frontend_test_data.py
  tests/test_qvain_utils.py
Labels: refactor-improve, python

#860 CSCFAIRMETA-1087: Functionality for detecting unsupported values in dataset
  etsin_finder/frontend/__tests__/__testdata__/qvain.maximalDataset.js
  etsin_finder/frontend/__tests__/combined/qvain/qvain.actors.test.jsx
  etsin_finder/frontend/__tests__/stores/view/qvain.accessType.test.js
  etsin_finder/frontend/__tests__/stores/view/qvain.apiv2.test.jsx
  etsin_finder/frontend/__tests__/stores/view/qvain.project.test.js
  etsin_finder/frontend/__tests__/stores/view/qvain.provenances.test.jsx
  etsin_finder/frontend/__tests__/stores/view/qvain.relatedResources.test.js
  etsin_finder/frontend/__tests__/stores/view/qvain.unsupported.test.js
  etsin_finder/frontend/__tests__/stores/view/usedEntities.test.js
  etsin_finder/frontend/js/components/qvain/fields/project/utils.jsx
  etsin_finder/frontend/js/stores/view/qvain/index.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.accessType.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.actors.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.datasetLanguage.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.fieldOfScience.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.infrastructure.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.license.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.otherIdentifier.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.project.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.provenances.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.relatedResources.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.spatials.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.subjectHeadings.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.usedEntities.js
  etsin_finder/frontend/js/stores/view/qvain/track.js
Labels: bugfix, refactor-improve

#863 CSCFAIRMETA-1120 new Used entities gets saved when the user cancels edited provenance
  etsin_finder/frontend/__tests__/combined/qvain/qvain.regression.test.jsx
  etsin_finder/frontend/__tests__/stores/view/qvain.spatial.test.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.spatials.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.usedEntities.js
Labels: bugfix, javascript

#867 CSCFAIRMETA-1063: All project members can view and edit dataset
  etsin_finder/app.py
  etsin_finder/auth/authorization.py
  etsin_finder/cache.py
  etsin_finder/resources/qvain_resources.py
  etsin_finder/services/cr_service.py
  etsin_finder/utils/flags.py
  etsin_finder/utils/qvain_utils.py
  tests/test_authorization.py
  tests/test_qvain_utils.py
Labels: new feature

#864 CSCFAIRMETA-1088: Show unsupported dataset fields in Qvain
  etsin_finder/frontend/__tests__/combined/qvain/qvain.unsupported.test.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/dataset.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/unsupported.jsx
  etsin_finder/frontend/locale/english/qvain.js
  etsin_finder/frontend/locale/finnish/qvain.js
  etsin_finder/utils/flags.py
Labels: new feature

#871 CSCFAIRMETA-1135: Add MATOMO_URL to app_config
  etsin_finder/app_config.py
  etsin_finder/frontend/static/index.template.ejs
  etsin_finder/frontend/webpack.config.js
  etsin_finder/frontend/webpack.dev.js
  etsin_finder/frontend/webpack.prod.js
  etsin_finder/views/index_views.py
Labels: refactor-improve
