Repository CSCfi/etsin-finder, pull requests merged in 2021-02, with the labels that each got.

#700 CSCFAIRMETA-914: Fix login spinner getting stuck
  etsin_finder/frontend/js/components/general/loader.jsx
  etsin_finder/frontend/js/components/general/navigation/loginButton.jsx
Labels: bugfix

#703 CSCFAIRMETA-925: Fix broken scroll in modal for adding files
  etsin_finder/frontend/js/components/qvain/fields/files/ida/addItems.jsx
Labels: bugfix

#706 CSCFAIRMETA-925: Qvain editor accessibility tests
  .travis.yml
  etsin_finder/frontend/__tests__/__testdata__/dataset.att.js
  etsin_finder/frontend/__tests__/combined/qvain/a11y/qvain.editor.a11y.test.jsx
  etsin_finder/frontend/__tests__/combined/qvain/metadataModal.test.jsx
  etsin_finder/frontend/js/components/qvain/fields/licenses/restrictionGrounds.jsx
  etsin_finder/frontend/package-lock.json
  etsin_finder/frontend/package.json
Labels: refactor-improve

#712 CSCFAIRMETA-944: Unify Qvain page title styles
  etsin_finder/frontend/js/components/qvain/general/card/index.jsx
  etsin_finder/frontend/js/components/qvain/views/datasets/index.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/header.jsx
Labels: refactor-improve

#713 CSCFAIRMETA-945: Fix server error when dataset does not exist
  etsin_finder/utils/qvain_utils.py
Labels: bugfix

#711 CSCFAIRMETA-924: Qvain datasets page accessibility tests
  etsin_finder/frontend/__tests__/__testdata__/qvain.datasets.js
  etsin_finder/frontend/__tests__/combined/qvain/a11y/qvain.datasets.a11y.test.jsx
  etsin_finder/frontend/js/components/qvain/views/datasets/datasetGroup.jsx
  etsin_finder/frontend/js/components/qvain/views/datasets/pagination.jsx
  etsin_finder/frontend/js/components/qvain/views/datasets/table.jsx
  etsin_finder/frontend/js/stores/domain/auth.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.datasets.js
Labels: refactor-improve

#709 CSCFAIRMETA-923: Qvain frontpage accessibility tests
  etsin_finder/frontend/__mocks__/imageMock.js
  etsin_finder/frontend/__tests__/combined/general/a11y/footer.a11y.test.jsx
  etsin_finder/frontend/__tests__/combined/qvain/a11y/qvain.header.a11y.test.jsx
  etsin_finder/frontend/__tests__/combined/qvain/a11y/qvain.landingPage.a11y.test.jsx
  etsin_finder/frontend/package.json
Labels: refactor-improve

#707 CSCFAIRMETA-617: Move access granter from query parameter to field
  etsin_finder/resources/qvain_resources.py
  etsin_finder/resources/qvain_resources_v2.py
  etsin_finder/utils/qvain_utils.py
  etsin_finder/utils/qvain_utils_v2.py
Labels: bugfix

#708 CSCFAIRMETA-935: Use secure cookie for cookie notification
  etsin_finder/frontend/js/layout/cookiesNotification.jsx
Labels: new feature

#704 CSCFAIRMETA-939: Fix submit action order
  etsin_finder/frontend/__tests__/combined/qvain/__snapshots__/qvain.test.legacy.jsx.snap
  etsin_finder/frontend/__tests__/stores/view/qvain.apiv2.test.jsx
  etsin_finder/frontend/js/stores/view/qvain/qvain.submit.js
Labels: bugfix, refactor-improve

#705 CSCFAIRMETA-900: "Download dataset metadata" info fixes
  etsin_finder/frontend/js/components/dataset/formatselect.jsx
  etsin_finder/frontend/js/components/qvain/general/section/tooltip.jsx
Labels: bugfix

#702 CSCFAIRMETA-930: Friendlier dataset download access errors
  etsin_finder/auth/authorization.py
  etsin_finder/frontend/js/components/dataset/data/idaResourcesV2/errorMessage.jsx
  etsin_finder/resources/download_resources_v2.py
  etsin_finder/resources/etsin_resources.py
  etsin_finder/utils/constants.py
  tests/basetest.py
  tests/test_authorization.py
  tests/test_data.json
Labels: new feature

#699 CSCFAIRMETA-913: Fix SSO language cookie config not being passed
  etsin_finder/resources/etsin_resources.py
Labels: bugfix

#691 CSCFAIRMETA-892: Use error boundaries in Qvain
  etsin_finder/frontend/__tests__/combined/qvain/__snapshots__/qvain.actors.test.jsx.snap
  etsin_finder/frontend/__tests__/combined/qvain/__snapshots__/qvain.test.jsx.snap
  etsin_finder/frontend/__tests__/combined/qvain/__snapshots__/qvain.test.legacy.jsx.snap
  etsin_finder/frontend/__tests__/combined/qvain/fieldErrorBoundary.test.jsx
  etsin_finder/frontend/__tests__/combined/qvain/qvain.files.legacy.jsx
  etsin_finder/frontend/__tests__/combined/qvain/qvain.test.jsx
  etsin_finder/frontend/__tests__/combined/qvain/qvain.test.legacy.jsx
  etsin_finder/frontend/__tests__/combined/qvain/qvainPas.legacy.test.jsx
  etsin_finder/frontend/js/components/dataset/data/idaResourcesV2/errorMessage.jsx
  etsin_finder/frontend/js/components/general/errorBoundary.jsx
  etsin_finder/frontend/js/components/qvain/fields/actors/field/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/actors/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/description/fieldOfScience/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/description/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/description/issuedDate/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/description/keywords/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/description/language/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/description/otherIdentifier/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/description/subjectHeadings/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/description/titleAndDescription/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/history/infrastructure/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/history/provenance/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/history/relatedResource/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/licenses/accessType.jsx
  etsin_finder/frontend/js/components/qvain/fields/licenses/licenses.jsx
  etsin_finder/frontend/js/components/qvain/fields/project/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/temporalAndSpatial/spatial/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/temporalAndSpatial/temporal/index.jsx
  etsin_finder/frontend/js/components/qvain/general/errors/fieldErrorBoundary.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/editor.styled.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/stickyHeader.jsx
  etsin_finder/frontend/js/components/qvain/views/main/index.jsx
  etsin_finder/frontend/locale/english.js
  etsin_finder/frontend/locale/finnish.js
Labels: new feature

#710 Cscfairmeta 933 submit button validation error tranlate not working
  etsin_finder/frontend/__tests__/combined/qvain/__snapshots__/qvain.test.jsx.snap
  etsin_finder/frontend/__tests__/combined/qvain/__snapshots__/qvain.test.legacy.jsx.snap
  etsin_finder/frontend/__tests__/combined/qvain/qvain.test.jsx
  etsin_finder/frontend/__tests__/stores/view/qvain.apiv2.test.jsx
  etsin_finder/frontend/js/components/qvain/fields/description/titleAndDescription/descriptionFieldInput.jsx
  etsin_finder/frontend/js/components/qvain/fields/description/titleAndDescription/descriptionFieldTextField.jsx
  etsin_finder/frontend/js/components/qvain/fields/project/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/temporalAndSpatial/temporal/temporalFieldContent.jsx
  etsin_finder/frontend/js/components/qvain/general/errors/validationError.jsx
  etsin_finder/frontend/js/components/qvain/general/header/tooltipHoverOnSave.jsx
  etsin_finder/frontend/js/components/qvain/general/modal/modalButtons.jsx
  etsin_finder/frontend/js/components/qvain/utils/formValidation.js
  etsin_finder/frontend/js/components/qvain/views/editor/submitButtonsV2.jsx
  etsin_finder/frontend/locale/english.js
  etsin_finder/frontend/locale/finnish.js
Labels: bugfix, refactor-improve

#715 CSCFAIRMETA-947: Add coverage to package.json scripts
  .gitignore
  etsin_finder/frontend/package.json
Labels: refactor-improve

#719 CSCFAIRMETA-949: Replace Lato Thin with Lato Light
  etsin_finder/frontend/js/index.css
  etsin_finder/frontend/resources/fonts/lato/Lato-Light.ttf
  etsin_finder/frontend/resources/fonts/lato/Lato-Thin.ttf
Labels: refactor-improve

#720 CSCFAIRMETA-950: Fix provenance validation messages
  etsin_finder/frontend/js/components/qvain/utils/formValidation.js
Labels: bugfix

#721 CSCFAIRMETA-952: Fix provenances not being loaded
  etsin_finder/frontend/js/stores/view/qvain/qvain.provenances.js
Labels: bugfix

#718 CSCFAIRMETA-948: Don't open top-level directories automatically
  etsin_finder/frontend/js/components/dataset/data/idaResourcesV2/fileTree.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/ida/addItems.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/ida/addItemsTree.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/ida/selectedItemsTree.jsx
Labels: refactor-improve

#740 CSCFAIRMETA-967: Fix producer project bugs
  etsin_finder/frontend/js/components/qvain/fields/project/FundingAgency.jsx
  etsin_finder/frontend/js/components/qvain/fields/project/FundingOrganization.jsx
  etsin_finder/frontend/js/components/qvain/fields/project/index.jsx
Labels: bugfix

#739 CSCFAIRMETA-841: Update download service error messages
  etsin_finder/frontend/js/components/dataset/data/idaResourcesV2/errorMessage.jsx
  etsin_finder/frontend/js/styles/globalStyles.jsx
  etsin_finder/frontend/locale/english.js
  etsin_finder/frontend/locale/finnish.js
Labels: refactor-improve

#738 CSCFAIRMETA-941: Shorten long filenames in Etsin
  etsin_finder/frontend/js/components/dataset/data/idaResourcesV2/fileTreeItem.jsx
  etsin_finder/frontend/js/components/general/files/items.jsx
Labels: refactor-improve

#732 CSCFAIRMETA-961: Fix Etsin tabs not updating when active version is changed
  etsin_finder/frontend/js/components/dataset/index.jsx
Labels: bugfix

#731 CSCFAIRMETA-963: Update cookie notification to match fairdata-ui better
  etsin_finder/frontend/__tests__/combined/general/a11y/cookiesNotification.a11y.test.jsx
  etsin_finder/frontend/js/layout/cookiesNotification.jsx
  etsin_finder/frontend/locale/english.js
  etsin_finder/frontend/locale/finnish.js
  etsin_finder/frontend/static/images/closeCookiesNotification.svg
  etsin_finder/frontend/static/images/closeCookiesNotificationHover.svg
Labels: refactor-improve

#733 CSCFAIRMETA-962: Fix "back to datasets" alignment
  etsin_finder/frontend/js/components/qvain/views/editor/editor.styled.jsx
Labels: bugfix

#735 CSCFAIRMETA-942: Redirect invalid tab urls to dataset tab
  etsin_finder/frontend/js/components/dataset/content.jsx
Labels: refactor-improve

#734 CSCFAIRMETA-938: Improve file loading and error handling
  etsin_finder/frontend/js/components/general/files/tree.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/ida/addItemsTree.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/ida/index.jsx
  etsin_finder/frontend/locale/english.js
  etsin_finder/frontend/locale/finnish.js
  etsin_finder/resources/common_resources_v2.py
  etsin_finder/views/dev_views.py
Labels: refactor-improve

#741 Merge test to stable v0.9.37-rc1
  etsin_finder/frontend/__tests__/combined/general/a11y/cookiesNotification.a11y.test.jsx
  etsin_finder/frontend/js/components/dataset/content.jsx
  etsin_finder/frontend/js/components/dataset/data/idaResourcesV2/errorMessage.jsx
  etsin_finder/frontend/js/components/dataset/data/idaResourcesV2/fileTreeItem.jsx
  etsin_finder/frontend/js/components/dataset/index.jsx
  etsin_finder/frontend/js/components/general/files/items.jsx
  etsin_finder/frontend/js/components/general/files/tree.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/ida/addItemsTree.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/ida/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/project/FundingAgency.jsx
  etsin_finder/frontend/js/components/qvain/fields/project/FundingOrganization.jsx
  etsin_finder/frontend/js/components/qvain/fields/project/index.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/editor.styled.jsx
  etsin_finder/frontend/js/layout/cookiesNotification.jsx
  etsin_finder/frontend/js/styles/globalStyles.jsx
  etsin_finder/frontend/locale/english.js
  etsin_finder/frontend/locale/finnish.js
  etsin_finder/frontend/static/images/closeCookiesNotification.svg
  etsin_finder/frontend/static/images/closeCookiesNotificationHover.svg
  etsin_finder/resources/common_resources_v2.py
  etsin_finder/views/dev_views.py
Labels: release-candidate
