Repository CSCfi/etsin-finder, pull requests merged in 2021-01, with the labels that each got.

#667 CSCFAIRMETA-850: Fix login through SSO for users without IDA groups
  etsin_finder/authentication.py
Labels: bugfix

#676 Cscfairmeta 867 tests for multi language field
  etsin_finder/frontend/__tests__/stores/view/qvain.multiLanguageField.test.js
Labels: refactor-improve

#671 CSCFAIRMETA-673: Label and other form fixes
  etsin_finder/frontend/__tests__/combined/qvain/__snapshots__/qvain.test.jsx.snap
  etsin_finder/frontend/js/components/qvain/fields/description/issuedDate/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/description/keywords/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/description/titleAndDescription/descriptionFieldInput.jsx
  etsin_finder/frontend/js/components/qvain/fields/description/titleAndDescription/descriptionFieldTextField.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/dataCatalog.jsx
  etsin_finder/frontend/js/components/qvain/fields/history/infrastructure/InfrastructureSelection.jsx
  etsin_finder/frontend/js/components/qvain/fields/history/infrastructure/index.jsx
  etsin_finder/frontend/js/components/qvain/general/input/stringArray.jsx
  etsin_finder/frontend/js/components/qvain/general/section/field.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/dataset.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/submitButtons.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/submitButtonsV2.jsx
Labels: refactor-improve

#674 CSCFAIRMETA-843: Fix crash when resource name is missing
  etsin_finder/frontend/__tests__/combined/qvain/__snapshots__/qvain.test.legacy.jsx.snap
  etsin_finder/frontend/js/components/qvain/general/section/fieldList.jsx
  etsin_finder/frontend/js/stores/view/locale.js
Labels: bugfix

#680 CSCFAIRMETA-773: Fix qvain_resources.py
  etsin_finder/resources/qvain_resources.py
Labels: bugfix

#678 CSCFAIRMETA-861 tests for qvain.field
  etsin_finder/frontend/__tests__/stores/view/qvain.field.test.js
Labels: refactor-improve

#682 Edit style of identifier to fit-content to remove emty space for shor…
  etsin_finder/frontend/js/components/dataset/identifier.jsx
Labels: refactor-improve

#686 CSCFAIRMETA-894: Fix Etsin login endpoint
  etsin_finder/views/auth_views.py
Labels: bugfix

#651 CSCFAIRMETA-246-add-fonts-to-stack
  etsin_finder/frontend/js/index.css
  etsin_finder/frontend/js/index.jsx
  etsin_finder/frontend/resources/fonts/lato/Lato-Bold.ttf
  etsin_finder/frontend/resources/fonts/lato/Lato-Regular.ttf
  etsin_finder/frontend/resources/fonts/lato/Lato-Thin.ttf
  etsin_finder/frontend/resources/fonts/lato/OFL.txt
Labels: new feature

#670 Cscfairmeta 851 access test cleanup
  etsin_finder/frontend/__tests__/stores/view/access.test.jsx
Labels: refactor-improve

#618 Cscfairmeta 794, 542, 642 draft validation and more reactive submit buttons
  etsin_finder/frontend/__tests__/combined/qvain/__snapshots__/qvain.test.legacy.jsx.snap
  etsin_finder/frontend/__tests__/components/qvain/qvain.submitButtonsV2.test.jsx
  etsin_finder/frontend/__tests__/stores/view/qvain.apiv2.test.jsx
  etsin_finder/frontend/__tests__/stores/view/qvain.referenceField.test.js
  etsin_finder/frontend/js/components/general/flaggedComponent.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/dataCatalog.jsx
  etsin_finder/frontend/js/components/qvain/general/header/tooltipHoverOnSave.jsx
  etsin_finder/frontend/js/components/qvain/general/input/stringArray.jsx
  etsin_finder/frontend/js/components/qvain/utils/formValidation.js
  etsin_finder/frontend/js/components/qvain/utils/handleSubmit.js
  etsin_finder/frontend/js/components/qvain/utils/responseError.js
  etsin_finder/frontend/js/components/qvain/views/editor/stickyHeader.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/submitButtons.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/submitButtonsV1.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/submitButtonsV2.jsx
  etsin_finder/frontend/js/components/qvain/views/main/index.jsx
  etsin_finder/frontend/js/stores/view/qvain/index.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.keyword.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.otherIdentifier.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.referenceField.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.submit.js
  etsin_finder/frontend/js/utils/constants.js
  etsin_finder/frontend/locale/english.js
  etsin_finder/frontend/locale/finnish.js
  etsin_finder/frontend/package-lock.json
  etsin_finder/frontend/package.json
  etsin_finder/resources/qvain_resources.py
  etsin_finder/resources/qvain_resources_v2.py
  etsin_finder/schemas/qvain_dataset_schema_v2.py
  etsin_finder/utils/qvain_utils.py
Labels: new feature

#628 CSCFAIRMETA-770: Get language cookie settings from backend
  etsin_finder/frontend/__tests__/combined/qvain/__snapshots__/qvain.test.legacy.jsx.snap
  etsin_finder/frontend/js/app.jsx
  etsin_finder/frontend/js/stores/domain/env.js
  etsin_finder/frontend/js/stores/view/locale.js
  etsin_finder/frontend/js/utils/cookies.jsx
  etsin_finder/frontend/static/index.template.ejs
Labels: new feature

#660 CSCFAIRMETA-833: Allow adding files if published version has no files
  etsin_finder/frontend/__tests__/combined/qvain/__snapshots__/qvain.test.legacy.jsx.snap
  etsin_finder/frontend/js/stores/view/common.files.js
  etsin_finder/frontend/js/stores/view/qvain/index.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.submit.js
Labels: new feature

#677 CSCFAIRMETA-841: Download service error handling improvements
  etsin_finder/frontend/__tests__/__testdata__/download.data.js
  etsin_finder/frontend/__tests__/combined/etsin/download.test.jsx
  etsin_finder/frontend/__tests__/combined/qvain/__snapshots__/qvain.test.legacy.jsx.snap
  etsin_finder/frontend/js/components/dataset/data/idaResourcesV2/download.js
  etsin_finder/frontend/js/components/dataset/data/idaResourcesV2/downloadActions.js
  etsin_finder/frontend/js/components/dataset/data/idaResourcesV2/errorMessage.jsx
  etsin_finder/frontend/js/components/dataset/data/idaResourcesV2/index.jsx
  etsin_finder/frontend/js/stores/view/common.files.js
  etsin_finder/frontend/js/stores/view/packages.js
  etsin_finder/frontend/locale/english.js
  etsin_finder/frontend/locale/finnish.js
  etsin_finder/services/download_service_v2.py
  etsin_finder/utils/request_utils.py
  tests/test_download.py
Labels: refactor-improve

#679 CSCFAIRMETA-304: Don't show datasets from harvested catalogs in Qvain
  etsin_finder/resources/common_resources_v2.py
  etsin_finder/resources/qvain_resources.py
  etsin_finder/resources/qvain_resources_v2.py
  etsin_finder/resources/qvain_rpc.py
  etsin_finder/resources/qvain_rpc_v2.py
  etsin_finder/schemas/qvain_dataset_schema.py
  etsin_finder/schemas/qvain_dataset_schema_v2.py
  etsin_finder/services/qvain_service.py
  etsin_finder/services/qvain_service_v2.py
  etsin_finder/utils/qvain_utils.py
  etsin_finder/utils/qvain_utils_v2.py
  tests/test_qvain_schema.py
Labels: refactor-improve

#683 CSCFAIRMETA-402: Fix remote resource URL input not being cleared
  etsin_finder/frontend/js/components/qvain/fields/files/external/externalFiles.jsx
  etsin_finder/frontend/js/stores/view/qvain/index.js
Labels: bugfix

#688 Fix package-lock.json to reflect new changes
  etsin_finder/frontend/package-lock.json
Labels: refactor-improve

#692 CSCFAIRMETA-909: Fix only first character of spatial being shown
  etsin_finder/frontend/js/stores/view/locale.js
Labels: bugfix

#694 CSCFAIRMETA-911: Access type bugs
  etsin_finder/frontend/js/components/qvain/fields/licenses/embargoExpires.jsx
  etsin_finder/frontend/js/components/qvain/fields/licenses/restrictionGrounds.jsx
Labels: bugfix

#696 Merge test to stable v0.9.35-rc2
  etsin_finder/frontend/js/components/qvain/fields/licenses/embargoExpires.jsx
  etsin_finder/frontend/js/components/qvain/fields/licenses/restrictionGrounds.jsx
Labels: release-candidate
