Repository CSCfi/etsin-finder, pull requests merged in 2021-09, with the labels that each got.

#873 CSCFAIRMETA-1124 Total package size limit check added to Package creation
  etsin_finder/resources/common_resources.py
  etsin_finder/resources/download_resources.py
  etsin_finder/services/common_service.py
  tests/test_download.py
Labels: new feature, python

#874 CSCFAIRMETA-1138: Disable download buttons for drafts
  etsin_finder/frontend/__tests__/combined/etsin/download.test.jsx
  etsin_finder/frontend/js/components/dataset/content.jsx
  etsin_finder/frontend/js/components/dataset/data/idaResources/downloadActions.js
  etsin_finder/frontend/js/components/dataset/data/idaResources/index.jsx
  etsin_finder/frontend/js/components/dataset/data/index.jsx
  etsin_finder/frontend/js/stores/view/datasetquery.js
  etsin_finder/frontend/locale/english/index.js
Labels: bugfix

#879 CSCFAIRMETA-1149: Fix error when removing actor with only provenance role
  etsin_finder/frontend/js/stores/view/qvain/qvain.actors.js
Labels: bugfix

#878 Cscfairmeta 1139 some fields dont warn on unsaved changes
  etsin_finder/frontend/__tests__/stores/view/qvain.field.test.js
  etsin_finder/frontend/__tests__/stores/view/qvain.project.test.js
  etsin_finder/frontend/__tests__/stores/view/qvain.temporal.test.js
  etsin_finder/frontend/js/components/qvain/general/section/fieldListAdd.jsx
  etsin_finder/frontend/js/stores/view/qvain/qvain.field.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.project.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.provenances.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.temporals.js
Labels: bugfix

#872 Cscfairmeta 1109 test suite for cache
  etsin_finder/app_config.py
  etsin_finder/cache.py
  test_requirements.txt
  tests/test_cache.py
Labels: refactor-improve, python

#869 Cscfairmeta 1142 test suite for utils
  etsin_finder/utils/utils.py
  tests/test_utils.py
  tests/testfiles/json_test_file_read.json
  tests/testfiles/json_test_file_write.json
  tests/utils_test.py
  tests/utils_test_data.py
Labels: refactor-improve, python

#870 CSCFAIRMETA-1128: Refactor actor saving
  etsin_finder/frontend/__tests__/__testdata__/qvain.actors.data.js
  etsin_finder/frontend/__tests__/combined/qvain/__snapshots__/qvain.actors.test.jsx.snap
  etsin_finder/frontend/__tests__/combined/qvain/__snapshots__/qvain.files.test.jsx.snap
  etsin_finder/frontend/__tests__/combined/qvain/qvain.actors.test.jsx
  etsin_finder/frontend/__tests__/combined/qvain/qvain.test.jsx
  etsin_finder/frontend/__tests__/stores/view/qvain.actorsRef.test.js
  etsin_finder/frontend/__tests__/stores/view/qvain.apiv2.test.jsx
  etsin_finder/frontend/__tests__/stores/view/qvain.project.test.js
  etsin_finder/frontend/__tests__/utils/utils.handleSubmit.test.js
  etsin_finder/frontend/__tests__/utils/utils.removeEmpty.js
  etsin_finder/frontend/js/components/qvain/fields/actors/modal/actorRadio.jsx
  etsin_finder/frontend/js/components/qvain/fields/actors/modal/person/personInput.jsx
  etsin_finder/frontend/js/components/qvain/utils/handleSubmit.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.actors.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.project.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.submit.schemas.js
  etsin_finder/frontend/js/utils/constants.js
  etsin_finder/frontend/js/utils/removeEmpty.js
  etsin_finder/schemas/qvain_dataset_schema.py
  etsin_finder/schemas/qvain_dataset_schema_v2.py
  etsin_finder/utils/qvain_utils.py
  requirements.txt
  tests/frontend_test_data.py
  tests/test_qvain_schema.py
  tests/test_qvain_utils.py
Labels: refactor-improve

#861 CSCFAIRMETA-1076 refactor and clean up
  etsin_finder/frontend/__tests__/combined/qvain/qvain.regression.test.jsx
  etsin_finder/frontend/__tests__/components/general/qvain.input.test.jsx
  etsin_finder/frontend/__tests__/components/general/qvain.modalContent.test.jsx
  etsin_finder/frontend/__tests__/components/general/qvain.modalInput.test.jsx
  etsin_finder/frontend/__tests__/components/general/qvain.modalReferenceInput.test.jsx
  etsin_finder/frontend/__tests__/components/general/qvain.translationTabInputModal.test.jsx
  etsin_finder/frontend/__tests__/components/qvain/qvain.provenance.test.jsx
  etsin_finder/frontend/__tests__/components/qvain/qvain.relatedResource.test.jsx
  etsin_finder/frontend/__tests__/components/qvain/qvain.spatial.test.jsx
  etsin_finder/frontend/__tests__/components/qvain/qvain.temporal.test.jsx
  etsin_finder/frontend/__tests__/stores/view/qvain.provenances.locations.test.js
  etsin_finder/frontend/__tests__/stores/view/qvain.provenances.test.jsx
  etsin_finder/frontend/js/app.jsx
  etsin_finder/frontend/js/components/qvain/fields/history/provenance/ProvenanceFieldContent.jsx
  etsin_finder/frontend/js/components/qvain/fields/history/provenance/form/actorsInput.jsx
  etsin_finder/frontend/js/components/qvain/fields/history/provenance/form/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/history/provenance/form/locationInput.jsx
  etsin_finder/frontend/js/components/qvain/fields/history/provenance/form/usedEntityInput.jsx
  etsin_finder/frontend/js/components/qvain/fields/history/relatedResource/form/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/history/relatedResource/relatedResourceContent.jsx
  etsin_finder/frontend/js/components/qvain/fields/temporalAndSpatial/spatial/SpatialFieldContent.jsx
  etsin_finder/frontend/js/components/qvain/fields/temporalAndSpatial/spatial/form/SpatialArrayInput.jsx
  etsin_finder/frontend/js/components/qvain/fields/temporalAndSpatial/spatial/form/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/temporalAndSpatial/temporal/index.jsx
  etsin_finder/frontend/js/components/qvain/fields/temporalAndSpatial/temporal/temporalFieldContent.jsx
  etsin_finder/frontend/js/components/qvain/general/input/durationpicker.jsx
  etsin_finder/frontend/js/components/qvain/general/input/translationTabInputModal.jsx
  etsin_finder/frontend/js/components/qvain/general/modal/modalContent.jsx
  etsin_finder/frontend/js/components/qvain/general/modal/modalInput.jsx
  etsin_finder/frontend/js/components/qvain/general/modal/modalReferenceInput.jsx
  etsin_finder/frontend/js/components/qvain/general/section/fieldList.jsx
  etsin_finder/frontend/js/components/qvain/general/section/fieldListAdd.jsx
  etsin_finder/frontend/js/stores/view/qvain/qvain.provenances.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.provenances.locations.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.spatials.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.temporals.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.usedEntities.js
  etsin_finder/frontend/jsconfig.json
  etsin_finder/frontend/package.json
  etsin_finder/frontend/webpack.dev.js
  etsin_finder/frontend/webpack.prod.js
  test_requirements.txt
Labels: refactor-improve

#882 CSCFAIRMETA-1129: Refactor saving of reference data field
  etsin_finder/frontend/__tests__/combined/qvain/__snapshots__/qvain.files.test.jsx.snap
  etsin_finder/frontend/__tests__/stores/view/qvain.fieldOfScience.test.js
  etsin_finder/frontend/__tests__/stores/view/qvain.referenceField.test.js
  etsin_finder/frontend/__tests__/utils/utils.handleSubmit.test.js
  etsin_finder/frontend/js/components/qvain/utils/handleSubmit.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.fieldOfScience.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.referenceField.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.subjectHeadings.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.submit.schemas.js
  etsin_finder/schemas/qvain_dataset_schema.py
  etsin_finder/schemas/qvain_dataset_schema_v2.py
  etsin_finder/utils/qvain_utils.py
  tests/frontend_test_data.py
Labels: refactor-improve

#883 CSCFAIRMETA-1132: Refactor saving remote resource
  etsin_finder/frontend/__tests__/combined/qvain/qvain.test.jsx
  etsin_finder/frontend/__tests__/utils/utils.handleSubmit.test.js
  etsin_finder/frontend/js/components/qvain/fields/files/dataCatalog.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/external/externalFileForm.jsx
  etsin_finder/frontend/js/components/qvain/fields/files/external/externalFiles.jsx
  etsin_finder/frontend/js/components/qvain/utils/getReferenceData.js
  etsin_finder/frontend/js/components/qvain/utils/handleSubmit.js
  etsin_finder/frontend/js/components/qvain/utils/select.js
  etsin_finder/frontend/js/stores/view/qvain/index.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.dataCatalog.schemas.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.externalResources.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.field.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.resources.js
  etsin_finder/schemas/qvain_dataset_schema.py
  etsin_finder/schemas/qvain_dataset_schema_v2.py
  etsin_finder/utils/qvain_utils.py
  tests/frontend_test_data.py
  tests/test_qvain_utils.py
Labels: refactor-improve

#886 CSCFAIRMETA-1160: Refactor saving access rights
  etsin_finder/frontend/__tests__/combined/qvain/__snapshots__/qvain.files.test.jsx.snap
  etsin_finder/frontend/__tests__/stores/view/qvain.restrictionGrounds.test.js
  etsin_finder/frontend/__tests__/utils/utils.handleSubmit.test.js
  etsin_finder/frontend/js/components/qvain/general/errors/validationError.jsx
  etsin_finder/frontend/js/components/qvain/general/header/tooltipHoverOnSave.jsx
  etsin_finder/frontend/js/components/qvain/utils/handleSubmit.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.accessType.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.embargoExpDate.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.license.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.restrictionGrounds.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.submit.schemas.js
  etsin_finder/schemas/qvain_dataset_schema.py
  etsin_finder/schemas/qvain_dataset_schema_v2.py
  etsin_finder/utils/qvain_utils.py
  tests/frontend_test_data.py
  tests/test_qvain_utils.py
Labels: refactor-improve

#884 CSCFAIRMETA-1131: Refactor saving projects
  etsin_finder/frontend/__tests__/combined/qvain/__snapshots__/qvain.files.test.jsx.snap
  etsin_finder/frontend/__tests__/stores/view/qvain.project.test.js
  etsin_finder/frontend/__tests__/utils/utils.handleSubmit.test.js
  etsin_finder/frontend/js/components/qvain/utils/handleSubmit.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.project.js
  etsin_finder/schemas/qvain_dataset_schema.py
  etsin_finder/schemas/qvain_dataset_schema_v2.py
  etsin_finder/utils/qvain_utils.py
  tests/frontend_test_data.py
Labels: refactor-improve

#891 CSCFAIRMETA-1150: Remove contributor type description from project
  etsin_finder/frontend/__tests__/stores/view/qvain.project.test.js
  etsin_finder/frontend/js/components/qvain/fields/project/FundingAgency.jsx
  etsin_finder/frontend/js/components/qvain/fields/project/utils.jsx
  etsin_finder/frontend/js/components/qvain/general/input/organizationSelect.jsx
  etsin_finder/frontend/js/stores/view/qvain/qvain.project.js
  etsin_finder/frontend/locale/english/qvain.project.js
  etsin_finder/frontend/locale/finnish/qvain.project.js
  etsin_finder/schemas/qvain_dataset_schema.py
  tests/frontend_test_data.py
Labels: refactor-improve

#892 CSCFAIRMETA-1153: Tabs for new datasets view
  .flake8
  etsin_finder/frontend/__tests__/combined/qvain/a11y/qvain.datasetsV2.a11y.test.jsx
  etsin_finder/frontend/__tests__/components/qvain/qvain.datasetsV2.tabs.test.jsx
  etsin_finder/frontend/__tests__/stores/view/qvain.datasetsV2.tabs.test.js
  etsin_finder/frontend/js/components/qvain/views/datasetsV2/index.jsx
  etsin_finder/frontend/js/components/qvain/views/datasetsV2/tabs.jsx
  etsin_finder/frontend/js/layout/content.jsx
  etsin_finder/frontend/js/routes/index.jsx
  etsin_finder/frontend/js/stores/index.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.datasetsV2.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.datasetsV2.tabs.js
  etsin_finder/frontend/locale/english/qvain.datasets.js
  etsin_finder/frontend/locale/finnish/qvain.datasets.js
  etsin_finder/utils/flags.py
Labels: new feature

#888 CSCFAIRMETA-1126 allow utc string format on provenance time period selection
  etsin_finder/frontend/js/stores/view/qvain/qvain.provenances.js
  etsin_finder/frontend/js/utils/extendYup.js
Labels: bugfix, javascript

#889 CSCFAIRMETA-1080: Qvain write lock
  etsin_finder/app.py
  etsin_finder/auth/authorization.py
  etsin_finder/cache.py
  etsin_finder/frontend/__tests__/combined/qvain/a11y/qvain.datasets.a11y.test.jsx
  etsin_finder/frontend/__tests__/components/qvain/qvain.datasets.datasetActions.test.js
  etsin_finder/frontend/__tests__/components/qvain/qvain.main.test.jsx
  etsin_finder/frontend/__tests__/stores/view/qvain.lock.test.js
  etsin_finder/frontend/__tests__/stores/view/qvain.project.test.js
  etsin_finder/frontend/__tests__/utils/promiseManager.test.js
  etsin_finder/frontend/js/app.jsx
  etsin_finder/frontend/js/components/qvain/fields/project/FundingAgency.jsx
  etsin_finder/frontend/js/components/qvain/fields/project/FundingOrganization.jsx
  etsin_finder/frontend/js/components/qvain/fields/project/ProjectForm.jsx
  etsin_finder/frontend/js/components/qvain/fields/project/index.jsx
  etsin_finder/frontend/js/components/qvain/general/buttons/buttonContainers.jsx
  etsin_finder/frontend/js/components/qvain/general/header/tooltipHoverOnSave.jsx
  etsin_finder/frontend/js/components/qvain/general/input/organizationSelect.jsx
  etsin_finder/frontend/js/components/qvain/views/datasets/datasetActions.js
  etsin_finder/frontend/js/components/qvain/views/datasets/table.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/lockNotification.jsx
  etsin_finder/frontend/js/components/qvain/views/editor/stickyHeader.jsx
  etsin_finder/frontend/js/components/qvain/views/main/index.jsx
  etsin_finder/frontend/js/stores/domain/auth.js
  etsin_finder/frontend/js/stores/view/qvain/index.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.lock.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.project.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.submit.js
  etsin_finder/frontend/js/utils/promiseManager.js
  etsin_finder/frontend/locale/english/qvain.js
  etsin_finder/frontend/locale/finnish/qvain.js
  etsin_finder/resources/qvain_resources.py
  etsin_finder/resources/qvain_rpc.py
  etsin_finder/services/cr_service.py
  etsin_finder/services/qvain_lock_service.py
  etsin_finder/utils/flags.py
  etsin_finder/utils/qvain_utils.py
  tests/test_cache.py
  tests/test_qvain_lock.py
  tests/test_qvain_utils.py
Labels: new feature
