Repository CSCfi/etsin-finder, pull requests merged in 2021-04, with the labels that each got.

#766 CSCFAIRMETA-998: Upgrade to Webpack 5
  .travis.yml
  etsin_finder/frontend/package-lock.json
  etsin_finder/frontend/package.json
  etsin_finder/frontend/webpack.config.js
  etsin_finder/frontend/webpack.prod.js
Labels: do not merge, refactor-improve

#791 Configuration for React fast refresh
  etsin_finder/frontend/package-lock.json
  etsin_finder/frontend/package.json
  etsin_finder/frontend/webpack.dev.js
  etsin_finder/views/index_views.py
Labels: new feature

#793 CSCFAIRMETA-979: Package generation email notifications
  .travis.yml
  etsin_finder/app.py
  etsin_finder/frontend/__tests__/__testdata__/download.data.js
  etsin_finder/frontend/__tests__/combined/etsin/a11y/etsin.files.a11y.test.jsx
  etsin_finder/frontend/__tests__/combined/etsin/download.packageModal.test.jsx
  etsin_finder/frontend/__tests__/combined/etsin/download.test.jsx
  etsin_finder/frontend/__tests__/combined/qvain/__snapshots__/qvain.test.legacy.jsx.snap
  etsin_finder/frontend/__tests__/combined/qvain/qvain.files.test.jsx
  etsin_finder/frontend/__tests__/stores/view/package.test.js
  etsin_finder/frontend/js/app.jsx
  etsin_finder/frontend/js/browserHistory.js
  etsin_finder/frontend/js/components/dataset/data/idaResourcesV2/confirmPackageModal.jsx
  etsin_finder/frontend/js/components/dataset/data/idaResourcesV2/downloadActions.js
  etsin_finder/frontend/js/components/dataset/data/idaResourcesV2/fileTree.jsx
  etsin_finder/frontend/js/components/dataset/data/idaResourcesV2/index.jsx
  etsin_finder/frontend/js/components/dataset/data/idaResourcesV2/packageModal/common.jsx
  etsin_finder/frontend/js/components/dataset/data/idaResourcesV2/packageModal/index.jsx
  etsin_finder/frontend/js/components/dataset/data/idaResourcesV2/packageModal/notificationEmail.jsx
  etsin_finder/frontend/js/components/dataset/data/idaResourcesV2/packageModal/packageCreate.jsx
  etsin_finder/frontend/js/components/dataset/data/idaResourcesV2/packageModal/packagePending.jsx
  etsin_finder/frontend/js/components/dataset/data/idaResourcesV2/packageModal/packageSuccess.jsx
  etsin_finder/frontend/js/components/qvain/utils/urls.js
  etsin_finder/frontend/js/stores/view/common.files.js
  etsin_finder/frontend/js/stores/view/common.files.views.js
  etsin_finder/frontend/js/stores/view/datasetquery.js
  etsin_finder/frontend/js/stores/view/packages.js
  etsin_finder/frontend/js/stores/view/packages.notifications.js
  etsin_finder/frontend/js/stores/view/qvain/qvain.files.js
  etsin_finder/frontend/locale/english.js
  etsin_finder/frontend/locale/finnish.js
  etsin_finder/resources/download_resources_v2.py
  etsin_finder/resources/etsin_resources.py
  etsin_finder/schemas/services.py
  etsin_finder/services/cr_service.py
  etsin_finder/services/download_service_v2.py
  etsin_finder/utils/contact_utils.py
  etsin_finder/utils/crypto_utils.py
  etsin_finder/utils/flags.py
  etsin_finder/utils/localization.py
  requirements.txt
  tests/basetest.py
  tests/test_crypto_utils.py
  tests/test_download.py
Labels: new feature

#789 CSCFAIRMETA-1012: Avoid unhandled rejection when session expires
  etsin_finder/frontend/js/stores/domain/auth.js
  etsin_finder/resources/etsin_resources.py
Labels: bugfix

#799 CSCFAIRMETA-1006: Move Etsin citation button
  etsin_finder/frontend/.eslintrc
  etsin_finder/frontend/js/components/dataset/citation/citationButton.jsx
  etsin_finder/frontend/js/components/dataset/identifier.jsx
  etsin_finder/frontend/js/components/dataset/index.jsx
  etsin_finder/frontend/js/components/dataset/sidebar/index.jsx
  etsin_finder/frontend/js/components/general/button.jsx
  etsin_finder/frontend/js/components/general/flaggedComponent.jsx
  etsin_finder/frontend/locale/english.js
  etsin_finder/frontend/locale/finnish.js
  etsin_finder/frontend/package-lock.json
  etsin_finder/frontend/package.json
  etsin_finder/utils/flags.py
Labels: new feature

#800 CSCFAIRMETA-1010: Copy identifier to clipboard in URL format
  etsin_finder/frontend/js/components/dataset/identifier.jsx
Labels: refactor-improve

#798 CSCFAIRMETA-906: Always use URL for DOI/URN citations
  etsin_finder/frontend/__tests__/utils/cite.test.js
  etsin_finder/frontend/__tests__/utils/idnToLink.test.jsx
  etsin_finder/frontend/js/components/dataset/citation/cite/apa.js
  etsin_finder/frontend/js/components/dataset/citation/cite/chicago.js
  etsin_finder/frontend/js/components/dataset/citation/cite/citationBuilder.js
  etsin_finder/frontend/js/components/dataset/citation/cite/index.js
  etsin_finder/frontend/js/components/dataset/citation/cite/mla.js
  etsin_finder/frontend/js/components/dataset/citation/cite/utils.js
  etsin_finder/frontend/js/utils/idnToLink.jsx
Labels: refactor-improve

#797 CSCFAIRMETA-990: Hide source buttons when there is a common source
  etsin_finder/frontend/__tests__/combined/etsin/externalResources.test.jsx
  etsin_finder/frontend/js/components/dataset/data/externalResources/index.jsx
  etsin_finder/frontend/js/components/dataset/data/externalResources/resourceItem.jsx
Labels: refactor-improve

#796 CSCFAIRMETA-1008: Use common cookie notification js
  etsin_finder/frontend/__tests__/combined/general/a11y/cookiesNotification.a11y.test.jsx
  etsin_finder/frontend/fairdata-ui/notification.css
  etsin_finder/frontend/js/app.jsx
  etsin_finder/frontend/js/layout/cookiesNotification.jsx
  etsin_finder/frontend/js/layout/index.jsx
  etsin_finder/frontend/js/styles/globalStyles.jsx
  etsin_finder/frontend/locale/english.js
  etsin_finder/frontend/locale/finnish.js
  etsin_finder/frontend/static/index.template.ejs
  etsin_finder/views/index_views.py
Labels: refactor-improve

#684 CSCFAIRADM-367: Dockerization
  .gitignore
  README.md
  docker-compose-with-nginx.yml
  docker-compose.yml
  elasticsearch.yml
  etsin_finder/finder.py
  etsin_finder/frontend/package-lock.json
  etsin_finder/frontend/package.json
  etsin_finder/frontend/webpack.dev.js
  etsin_finder/frontend/webpack.dockerfile
  etsin_finder/views/index_views.py
  flask.dockerfile
Labels: refactor-improve

#804 CSCFAIRMETA-1025: Add BUILD env variable
  etsin_finder/frontend/.eslintrc
  etsin_finder/frontend/js/app.jsx
  etsin_finder/frontend/js/components/dataset/index.jsx
  etsin_finder/frontend/js/components/general/modal.jsx
  etsin_finder/frontend/js/index.jsx
  etsin_finder/frontend/js/stores/domain/env.flags.js
  etsin_finder/frontend/js/stores/domain/env.js
  etsin_finder/frontend/package.json
  etsin_finder/frontend/webpack.config.js
  etsin_finder/frontend/webpack.dev.js
  etsin_finder/frontend/webpack.prod.js
Labels: bugfix, refactor-improve

#801 CSCFAIRMETA-1007: Fix metadata response filename
  etsin_finder/app_config.py
  etsin_finder/services/download_metadata_service.py
  tests/test_download_metadata.py
Labels: bugfix

#794 CSCFAIRMETA-1013: Remove fd_language cookie
  etsin_finder/app.py
  etsin_finder/frontend/js/stores/view/locale.js
  etsin_finder/resources/etsin_resources.py
  etsin_finder/utils/localization.py
  etsin_finder/views/auth_views.py
Labels: refactor-improve

#809 CSCFAIRMETA-906: [FIX] Citation fixes
  etsin_finder/frontend/__tests__/utils/cite.test.js
  etsin_finder/frontend/js/components/dataset/citation/cite/utils.js
Labels: bugfix

#810 Merge test to stable v0.9.40-rc1
  etsin_finder/frontend/__tests__/utils/cite.test.js
  etsin_finder/frontend/js/components/dataset/citation/cite/utils.js
Labels: release-candidate

#811 Merge stable to master v0.9.40-rc1
  etsin_finder/frontend/__tests__/utils/cite.test.js
  etsin_finder/frontend/js/components/dataset/citation/cite/utils.js
Labels: release
